# Generated by Django 4.2.30 on 2026-09-22 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(default='D-114980 - 2 YEAR LTRA FOR CONDITION MONITORING OF PRIMARY AND DISTRIBUTION SUBSTATIONS IN ABU DHABI, AL AIN AND AL DHAFRA REG', max_length=500)),
                ('client', models.CharField(default='TAQA DISTRIBUTION', max_length=255)),
                ('contractor', models.CharField(default='DELTA STAR POWER PROJECT SERVICES S.P.L.L.C', max_length=255)),
                ('substation_id', models.CharField(max_length=100)),
                ('work_order', models.CharField(blank=True, default='', max_length=100)),
                ('ewo', models.CharField(blank=True, default='', max_length=100)),
                ('date_of_inspection', models.DateField()),
                ('prepared_by', models.CharField(blank=True, default='', max_length=255)),
                ('verified_by', models.CharField(blank=True, default='', max_length=255)),
                ('maximo_entry_by', models.CharField(blank=True, default='', max_length=255)),
                ('brief_text', models.TextField(default='Visual Civil, Visual, Thermal & PD')),
                ('summary_findings', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='reports.inspectionreport')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SectionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/inspection_images/')),
                ('caption', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='reports.reportsection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
