# Generated by Django 4.2.30 on 2026-09-22 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionimage',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
