# Generated by Django 4.2.30 on 2026-09-22 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_sectionimage_subtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='reports.reportsection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
