# Generated by Django 4.2.30 on 2026-09-23 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_sectionnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionnote',
            name='position',
            field=models.CharField(blank=True, default='top', max_length=50),
        ),
    ]
